### PR TITLE
Fix #1

### LINKED ISSUE #1: Tone lag in iOS 11
ToneGenerator1.0 works perfectly through iOS10. In iOS 11: Play the 440 hz tone then stop. Change the frequency, press start. The 440 Hz signal plays for a moment then the new tone is played. Change the frequency again and the old frequency plays for a moment before the new frequency.

### PR DESCRIPTION
**Pull request by ziyaointl**
Fix the lag issue with changing frequency after stopping the node by resetting audioEngine.

### CODE REVIEW

**Comment by ooper-shlab** [comment]
Thanks for your kind proposal. Unfortunately, I do not have enough time to check how much your proposal has improved the code. Give me a few more days, I'll check it this weekend.

**Comment by ziyaointl** [comment]
Sure. You are very welcome!

**Comment by ooper-shlab** [comment]
So, I have merged your pull request into my repository. As far as I tested, your solution is simple and effective enough. Thank you!

**Comment by ziyaointl** [comment]
No problem! Glad it worked

**Pull request merged**
